#+TITLE: Tests sur paramètre sur de position pour deux échantillons
#+AUTHOR: Ahmadou H. DICKO
#+DATE: Février 2014
#+startup: beamer
#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [xetex, bigger]
#+LATEX_HEADER: \usepackage{minted}
#+LATEX_HEADER: \usepackage{fancyvrb}
#+LATEX_HEADER: \definecolor{newgray}{rgb}{0.95, 0.95, 0.95}
#+LATEX_HEADER: \newminted{r}{fontsize=\small, bgcolor=newgray}
#+LATEX_HEADER: \DefineVerbatimEnvironment{verbatim}{Verbatim}{fontsize=\small, label=R output, frame=lines, labelposition=topline}
#+LATEX_HEADER: \setmainfont[Mapping=tex-text,Ligatures=Common]{Minion Pro}
#+LATEX_HEADER: \setsansfont[Mapping=tex-text,Ligatures=Common]{Myriad Pro}
#+LATEX_HEADER: \setmathfont[Scale=MatchLowercase]{Minion Pro}
#+LATEX_HEADER: \setmonofont[Scale=0.75]{Source Code Pro}
#+LATEX_HEADER: \institute[ENSAE]{ENSAE}
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)
#+BEAMER_THEME: Boadilla
#+BEAMER_COLOR_THEME: orchid
#+BEAMER_HEADER: \setbeamertemplate{navigation symbols}{}
#+PROPERTY: session *R*
#+PROPERTY: cache yes 
#+PROPERTY: exports both
#+PROPERTY: tangle yes
#+PROPERTY: results output graphics
#+OPTIONS: toc:nil H:2

#+LATEX:\selectlanguage{frenchb}
#+LATEX:\begin{frame}[t]{Plan}
#+LATEX:\tableofcontents
#+LATEX:\end{frame}

* Introduction
#+begin_src R :exports none :results silent :session
  library(Cairo)
  library(plyr)
  mainfont <- "Minion Pro"
  CairoFonts(regular = paste(mainfont, "style=Regular", sep=":"),
             bold = paste(mainfont, "style=Bold", sep=":"),
             italic = paste(mainfont, "style=Italic", sep=":"),
             bolditalic = paste(mainfont, "style=Bold Italic,BoldItalic", sep=":"))
  pdf <- CairoPDF
  options(prompt = "> ")
#+end_src
  
** Introduction							    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:

- Soit $\theta \in \mathbb{R}$ un paramètre de position.
- On supposera par la suite que $F_y(x) = F_x(x - \theta) \forall x \in \mathbb{R}$
- Il est possible de comparer la distribution en utilisant le paramètre
  de positition $\theta$ (typiquement la médiane).
- Les hypothèses sont alors les suivantes
- $H_0\ :\ \theta = 0$ : égalité entre $X$ et $Y$
- $H_1\ :\ \theta \neq 0$ : $X$ différent de $Y$

Les hypothèses alternatives suivantes peuvent aussi être considéré :
- $H_1\ :\ \theta > 0$ : $X$ stochastiquement supérieur à $Y$
- $H_1\ :\ \theta < 0$ : $X$ stochastiquement inférieur à $Y$

** Introduction 						    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t
   :END:

- Soit $X$ et $Y$ deux v.a dont les échantillons peuvent être de taille différentes
- Les procédures de test sur paramètre de distribution seront basées sur
  une famille de statistiques linéaires de rang particulières de la forme :

\[
S_N = \sum_{i = 1}^m a_N(R_i)
\]

- $R_i$ est le rang de $X_i$ dans l'échantillon $Z = (X_1, ..., X_m, Y_1, ..., Y_n)$ et on a $N = n + m$  
- les score $a_N$ sont croissants, non constant et construit à partir de fonction mesurable à valeurs dans $]0,\ 1[$

** Introduction							    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:

- Dans cette partie, nous présenterons deux tests de la même famille :
  - Le test de Wilcoxon
  - Le test de Mann-Whitney

* Test de Wilcoxon
#+LATEX:\begin{frame}{Plan}
#+LATEX:\tableofcontents[currentsection]
#+LATEX:\end{frame}
** Test de Wilcoxon : résolution 		    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:
La statistique de test corresponds à la statistique linéaire de rang avec
avec $a_N(i) = i, \forall 1\leq i \leq N$

\[
W_N = \sum_{i = 1}^m R_i
\]

Avec :
- $\displaystyle \mathbb{E}(W_N) = m \frac{m + n + 1}{2}$
- $\displaystyle \mathbb{V}(W_N) = m n \frac{m + n + 1}{12}$

** Test de Wilcoxon : résolution 		    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:
Sous $H_0$, $W_N$ est symétrique autour de sa moyenne et on a les
régions critiques suivantes :

- ${W_N\ \geq\ s_1}$ : ${\theta\ >\ 0}$ : dépendance positive
- ${W_N\ \leq\ s_2}$ : ${\theta\ <\ 0}$ : dépendance négative
- ${W_N\ \geq\ s_1\ ou\ W_N\ \leq\ s_2}$ : ${\theta\ \neq\ 0}$ : dépendance positive

** Test de Wilcoxon : résolution 		    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:
Sous $H_0$ :
- Pour de petites valeurs de $N$ les valeurs critiques 
  $s_1$ et $s_2$ sont tabulé.
- Pour $N > 30$ on peut utiliser l'approximation normale en considérant
  la v.a U :
   \[
   U = \frac{W_N - \mathbb{E}(W_N) - \frac{1}{2}}{\sigma(W_N)}
   \]

- $U \sim \mathcal{N}(0, 1)$ donc on utilise les valeurs critiques de
  la loi normale centrée réduite pour résoudre le problème de test.



** Test de Wilcoxon : exemple 					    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t
   :END:

*** 								   :B_column:
    :PROPERTIES:
    :BEAMER_col: 0.4   
    :BEAMER_env: block
    :END:
#+begin_src R :exports results 
  X <- c(980, 1305, 906, 1140, 1130, 1080, 1090, 1270, 1250, 1100)
  Y <- c(900, 1245, 910, 1220, 1010, 990, 1030, 1170, 1200, 1060)
  df <- data.frame(X, Y)
  df
#+end_src

*** 								   :B_column:
    :PROPERTIES:
    :BEAMER_env: column
    :BEAMER_col: 0.6
    :END:
#+begin_src R :exports results :results graphics :file ../figures/course4-spear-1.pdf :height 7 
  boxplot(X, Y, xaxt = "n")
  axis(1, at = c(1, 2), labels = c("X", "Y"))
  
#+end_src

** Test de Wilcoxon : exemple 			    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t
   :END:


#+begin_src R :exports code
  n <- length(X)
  m <- length(Y)
  R_x <- rank(c(X, Y), ties.method = "average")[1:n]  
  R_y <- rank(c(X, Y), ties.method = "average")[(n + 1):(m + n)]  
#+end_src


#+begin_src R :exports results
  n <- length(X)
  m <- length(Y)
  R_x <- rank(c(X, Y), ties.method = "average")[1:n]  
  R_y <- rank(c(X, Y), ties.method = "average")[(n + 1):(m + n)]
  df <- mutate(df, R_x = R_x, R_y = R_y)
  mat <- t(df)
  colnames(mat) <- seq(nrow(df))
  mat
#+end_src

** Test de Wilcoxon : exemple 			    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t
   :END:

#+begin_src R :exports both
  p <- 0.05
  W <- sum(R_x)
  N <- m + n
  E_W <- m * (N + 1) / 2
  V_W <- (m * n * (m + n + 1)) / 12
  U <- (W - E_W - 0.5) / sqrt(V_W)
  z_theo <- qnorm(p = 1 - p/2)
  c(W = W, U = U, z_theo = z_theo)
#+end_src

** Test de Wilcoxon : exemple 					    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t
   :END:

#+begin_src R :exports both
  abs(U) > z_theo
#+end_src

On ne peut rejetter l'hypothèse nulle de dépendance quelconque entre $X$ et $Y$ au seuil de 5%.

* Test de Mann-Whitney
#+LATEX:\begin{frame}{Plan}
#+LATEX:\tableofcontents[currentsection]
#+LATEX:\end{frame}
** Test de Mann-Whitney : résolution 				    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:
- Le test de Mann-Whitney encore appelé Wilcoxon Mann-Whitney est basé sur le test 
  Wilcoxon.
- Soit $W_N$, la statistique du test de Wilcoxon, alors la statistique de Mann-Whitney
  $U_N$ est définie par :

\[
U_N = W_N - \frac{m(m + 1)}{2}
\]

- $\displaystyle \mathbb{E}(U_N) = \frac{mn}{2}$

** Test de Mann-Whitney : résolution 				    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t
   :END:
- On peut montrer (exercice) que  :

\[
U_N = \sum_{i = 1}^m\sum_{j = 1}^n\mathrm{1}_{\mathbb{R^+}}(X_i - Y_j)
\]

Donc $U_N$ compte le nombre de fois où un $X$ est plus grand qu'un $Y$.
De plus il s'agit de la statistique du signe calculée sur les $mn$ différences $(X_i - Y_j)$.

** Test de Wilcoxon : résolution 		    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:
Sous $H_0$, $U_N$ est symétrique autour de sa moyenne et on a les
régions critiques suivantes :

- ${U_N\ \geq\ c}$ : ${\theta\ >\ 0}$ : dépendance positive
- ${U_N\ \leq\ mn-c}$ : ${\theta\ <\ 0}$ : dépendance négative
- ${U_N\ \geq\ c\ ou\ W_N\ \leq\ mn - c}$ : ${\theta\ \neq\ 0}$ : dépendance positive

Pour les petites valeurs de $N$, la loi de $U_N$ est tabulé et on considère l'approximation
normale pour de grands échantillons ($N > 30$) 

** Test de Mann-Whitney : exemple 				    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t
   :END:

#+begin_src R :exports both
  wilcox.test(X, Y) 
#+end_src

** Test de Mann-Whitney : exemple 				    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t
   :END:

On peut vérifier la relation entre $U_N$ et $W_N$ :

\[
U_N = W_N - \frac{m(m + 1)}{2}
\]


#+begin_src R :exports both
  wilcox.test(X, Y)$statistic ==  W - (m * (m + 1)) / 2  
#+end_src

* Cas des séries appariées
#+LATEX:\begin{frame}{Plan}
#+LATEX:\tableofcontents[currentsection]
#+LATEX:\end{frame}
** Cas des séries appariées 					    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:

- Considérons le cas de séries appariées, c'est à dire
  lorsque les deux échantillons $X$ et $Y$ représente les deux mesures
  que subissent une entitée statistique donnée.

- Dans cette configuration, les tests de Wilcoxon ou la variante de Mann-Whitney ne 
  sont plus applicables.

- Le test des signés permettent de résoudre ce problème :
  - On utilise le test de Wilcoxon signé (problème à un échantillon) sur les différences $D = X - Y$  
  - De manière analogue, on peut aussi utiliser le test du signe.
