#+TITLE: Problème à deux échantillons : Alternative générale
#+AUTHOR: Ahmadou H. DICKO
#+DATE: Février 2014
#+startup: beamer
#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [xetex, bigger]
#+LATEX_HEADER: \usepackage{minted}
#+LATEX_HEADER: \usepackage{fancyvrb}
#+LATEX_HEADER: \definecolor{newgray}{rgb}{0.95, 0.95, 0.95}
#+LATEX_HEADER: \newminted{r}{fontsize=\small, bgcolor=newgray}
#+LATEX_HEADER: \DefineVerbatimEnvironment{verbatim}{Verbatim}{fontsize=\small, label=R output, frame=lines, labelposition=topline}
#+LATEX_HEADER: \setmainfont[Mapping=tex-text,Ligatures=Common]{Minion Pro}
#+LATEX_HEADER: \setsansfont[Mapping=tex-text,Ligatures=Common]{Myriad Pro}
#+LATEX_HEADER: \setmathfont[Scale=MatchLowercase]{Minion Pro}
#+LATEX_HEADER: \setmonofont[Scale=0.75]{Source Code Pro}
#+LATEX_HEADER: \institute[ENSAE]{ENSAE}
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)
#+BEAMER_THEME: Boadilla
#+BEAMER_COLOR_THEME: orchid
#+BEAMER_HEADER: \setbeamertemplate{navigation symbols}{}
#+PROPERTY: session *R*
#+PROPERTY: cache yes 
#+PROPERTY: exports both
#+PROPERTY: tangle yes
#+PROPERTY: results output graphics
#+OPTIONS: toc:nil H:2

#+LATEX:\selectlanguage{frenchb}
#+LATEX:\begin{frame}[t]{Plan}
#+LATEX:\tableofcontents
#+LATEX:\end{frame}

* Introduction
#+begin_src R :exports none :results silent :session
  library(Cairo)
  mainfont <- "Minion Pro"
  CairoFonts(regular = paste(mainfont, "style=Regular", sep=":"),
             bold = paste(mainfont, "style=Bold", sep=":"),
             italic = paste(mainfont, "style=Italic", sep=":"),
             bolditalic = paste(mainfont, "style=Bold Italic,BoldItalic", sep=":"))
  pdf <- CairoPDF
  options(prompt = "> ")
#+end_src
  
** Introduction							    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:

- Nous avons vu comment comparer la distribution de deux v.a à travers  des tests sur
  paramètres de positions et d'échelles

- Il est cependant possible de considérer de tests à alternative générale pour comparer 
  deux distributions.

- Ces tests sont basés sur les propriétés essentielles de la fonction de répartition
  empirique.

- Nous présenterons brièvement deux tests  :
  - Le test de Kolmogorov Smirnov
  - Le test de Cramer-von Mises

* Fonction de répartition empirique
#+LATEX:\begin{frame}{Plan}
#+LATEX:\tableofcontents[currentsection]
#+LATEX:\end{frame}

** Définition 							    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:
Soit $F$ la fonction de répartition d'une v.a $X$ d'échantillon $(X_1, ..., X_n)$, on définit la fonction
de répartition empirique $F_n$ par  :

\[
F_n(x) = \frac{1}{n} \sum_{i = 1}^n \mathrm{1}_{(X_i \leq x)}
\]

Il s'agit d'un estimateur non paramétrique de la $F$ et c'est l'estimateur naturel.

** Propriétés							    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:

On suppose $(X_1, ..., X_n)$ i.i.d alors on a :

- $\mathbb{E}(F_n) = \frac{1}{n}\sum_{i = 1}^n \mathbb{P}(X_i \leq x) = F$ (estimateur sans biais)
- $\mathbb{V}(F_n) = \frac{1}{n} \mathbb{V}(\mathrm{1}_{X_i \leq x}) \longrightarrow 0$
- $F_n \longrightarrow F$, p.s (loi des grands nombre)
- $\sqrt{n}(F_n - F)(x) \longrightarrow \mathcal{N}(0, F(1-F)(x))$, en loi (TCL)
- $sup_{x \in \mathbb{R}}|(F_n - F)(x)| \longrightarrow 0$, p.s
 
* Test de Kolmogorov-Smirnov
  
** Test de Kolmogorov-Smirnov : résolution 		    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:
Le test de Kolmogorov-Smirnov est basé  les statistiques :

- $\displaystyle K_{mn}^+ = d^+(F_m, G_n) = sup_{x \in \mathbb{R}}[F_m(x) - G_n(x)]$
- $\displaystyle K_{mn}^+ = d^+(G_n, F_m) = sup_{x \in \mathbb{R}}[G_n(x) - F_m(x)]$
- $\displaystyle K_{mn} = max(K_{mn}^{+}, K_{mn}^{-}) = sup_{x \in \mathbb{R}}|F_m(x) - G_n(x)|$

Sous $H_0$, ces statistiques de rang ont une loi indépendante de $F$.

** Test de Kolmogorov-Smirnov : résolution 			    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:

Sous $H_0$, on a les lois limites des statistiques suivantes :
- $\displaystyle \mathbb{P}(\sqrt{\frac{mn}{N}}K_{mn}^+ > x) \longrightarrow e^{-2x^2} \mathrm{1}_{\mathbb{R^+}}(x)$
- $\displaystyle \mathbb{P}(\sqrt{\frac{mn}{N}}K_{mn}^- > x) \longrightarrow e^{-2x^2} \mathrm{1}_{\mathbb{R^+}}(x)$
- $\displaystyle \mathbb{P}(\sqrt{\frac{mn}{N}}K_{mn} > x) \longrightarrow 2 \sum_{k = 1}^{\infty} (-1)^{k - 1}e^{-2k^2 x^2} \mathrm{1}_{\mathbb{R^+}}(x)$

La région de rejet $W$ est du type définie par :
- ${K_{mn}^+ > c1}$ : $F > G$
- ${K_{mn}^{-} < c2}$ : $F < G$
- ${K_{mn} > c}$ : $F \neq G$

** Test de Kolmogorov-Smirnov : exemple 			    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:

#+begin_src R
  set.seed(123)
  X <- rnorm(100, mean = 10, sd = 5)
  Y <- rlnorm(100, meanlog = 3, sdlog = 2)
  ks.test(X, Y)
#+end_src

* Test de Cramer-von Mises
#+LATEX:\begin{frame}{Plan}
#+LATEX:\tableofcontents[currentsection]
#+LATEX:\end{frame}
** Test de Cramer-von Mises : résolution 			    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t      
   :END: 
- Le test de Cramer-von Mises est une alternative au test de Kolmogorov Smirnov.
- La statistique de test est la suivante :

\[
W_{mn}^2 = \frac{mn}{(m + n)^2} [\sum_{i = 1}^m (F_m(x_i) - G_n(x_i))^2 + \sum_{j = 1}^n (F_m(y_j) - G_n(y_j))^2]
\]

- Sous $H_0$, la région critique est la suivante $W_{mn}^2 > c$ pour le test bilatéral

** Test de Cramer-von Mises : exemple 			    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:

#+begin_src R :exports both 
  library(cramer)
  set.seed(123)
  X <- rnorm(100, mean = 10, sd = 5)
  Y <- rlnorm(100, meanlog = 3, sdlog = 2)
  cramer.test(X, Y)
  
#+end_src
   
