#+TITLE: Tests d'indépendance sur deux échantillon
#+AUTHOR: Ahmadou H. DICKO
#+DATE: Février 2014
#+startup: beamer
#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [xetex, bigger]
#+LATEX_HEADER: \usepackage{minted}
#+LATEX_HEADER: \usepackage{fancyvrb}
#+LATEX_HEADER: \definecolor{newgray}{rgb}{0.95, 0.95, 0.95}
#+LATEX_HEADER: \newminted{r}{fontsize=\small, bgcolor=newgray}
#+LATEX_HEADER: \DefineVerbatimEnvironment{verbatim}{Verbatim}{fontsize=\small, label=R output, frame=lines, labelposition=topline}
#+LATEX_HEADER: \setmainfont[Mapping=tex-text,Ligatures=Common]{Minion Pro}
#+LATEX_HEADER: \setsansfont[Mapping=tex-text,Ligatures=Common]{Myriad Pro}
#+LATEX_HEADER: \setmathfont[Scale=MatchLowercase]{Minion Pro}
#+LATEX_HEADER: \setmonofont[Scale=0.75]{Source Code Pro}
#+LATEX_HEADER: \institute[ENSAE]{ENSAE}
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)
#+BEAMER_THEME: Boadilla
#+BEAMER_COLOR_THEME: orchid
#+BEAMER_HEADER: \setbeamertemplate{navigation symbols}{}
#+PROPERTY: session *R*
#+PROPERTY: cache yes 
#+PROPERTY: exports both
#+PROPERTY: tangle yes
#+PROPERTY: results output graphics
#+OPTIONS: toc:nil H:2

#+LATEX:\selectlanguage{frenchb}
#+LATEX:\begin{frame}[t]{Plan}
#+LATEX:\tableofcontents
#+LATEX:\end{frame}

* Introduction
#+begin_src R :exports none :results silent :session
  library(Cairo)
  library(plyr)
  mainfont <- "Minion Pro"
  CairoFonts(regular = paste(mainfont, "style=Regular", sep=":"),
             bold = paste(mainfont, "style=Bold", sep=":"),
             italic = paste(mainfont, "style=Italic", sep=":"),
             bolditalic = paste(mainfont, "style=Bold Italic,BoldItalic", sep=":"))
  pdf <- CairoPDF
  options(prompt = "> ")
#+end_src
  
** Introduction							    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:

- Les procédures non paramétrique permettent de tester la structure de la dépendence
  au sein d'échantillon.
- Il est cependant possible de procéder à la comparaison d'échantillons issuent de 
  populations différentes.
- Cette comparaison se base sur les propriétés des statistique de rangs et de rangs signés
  et permettent de réaliser une comparaison à plusieurs niveau :
  - Relation de dépendance
  - Comparaison de paramètre de position
  - Comparaison de paramètre d'échelle
  - Comparaison de génerale de distribution
 
** Introduction							    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:

- Dans cette section, nous allons nous intéresser aux tests d'indépendances afin d'analyser
  les relation de dépendance entre deux v.a.
- Il existe de nombreuses procédures qui permettent de réaliser de tels comparaison.
- Dans cette section, deux tests d'hypothèse seront présentés afin de répondre à ces questions :
  - le test de Spearman
  - le test de Kendall



** Introduction							    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:

L'hypothèse qui sera utilisé afin de comparer les v.a est : 
- $H_0$ : $F(x,y) = F_x(x) F_y(y),\ \forall x, y \in \mathbb{R}$ 
- $H_1$ : $\exists x, y \in \mathbb{R},\ F(x, y) \neq F_x(x) F_y(y)$ (dépendance quelconque)

Il est possible d'avoir les alternatives suivantes :
- dépendance positive
- dépendance négative

* Test de Spearman
#+LATEX:\begin{frame}{Plan}
#+LATEX:\tableofcontents[currentsection]
#+LATEX:\end{frame}
** Test de Spearman : résolution 		    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:

- Soit X et Y deux v.a et soit $(X_1, ..., X_n)$ et $(Y_1, ...., Y_n)$
  deux réalisations de $X$ et $Y$ respectivement.
- Le test de Spearman permet de tester l'indépendance entre $X$ et $Y$ et plus
  généralement la relation de dépendance.  
- Il est similaire en construction au test de corrélation de rang du Spearman pour
  les problèmes à un échantillon.
- Le test de Spearman peut être construit via plusieurs statistiques qui permettent
  de répondre au même problème de test. 

** Test de Spearman : résolution 		    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:

- La première statistique qui va permettre tester l'indépedance entre $X$ et $Y$
  est basée sur les rangs de $(X_1, ..., X_n)$ et $(Y_1, ..., Y_n)$ que nous allons étudier est :

\[
S = \sum_{i=1}^n R_i Q_i
\]

Avec

\[
R_i = \sum_{i=1}^n \mathrm{1}_{\mathbb{R}_+} (X_i - X_j)
\]

\[
Q_i = \sum_{i=1}^n \mathrm{1}_{\mathbb{R}_+} (Y_i - Y_j)
\]

** Test de Spearman : résolution                    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:

- Pour faciliter le calculs de la statistique ainsi que ces propriétés, nous allons la reformuler.
- Considerons, de nouveau le couple de v.a $(X, Y)$ et soit $Z$ la v.a dont l'observation $Z_i$ est la réalisation 
  de $Y$ associée à $X_{(i)}$.
- Soit $T_i$ le rang de $Z_i$, on a alors :
   
\[
S = \sum_{i=1}^n i T_i
\]

** Test de Spearman : résolution 				    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:
La région de rejet $W$ pour ce test d'indépendance est définie par :
- ${S > s1}$ : dépendance positive
- ${S < s2}$ : dépendance négative
- ${S > s1\ ou\ S < s2}$ : dépendance quelconque

De plus sous $H_0$, la distribution de $S$ est symétrique autour de 
sa moyenne :
\[
\mathbb{E}(S) = \sum_{i = 1}^n i \mathbb{E}(T_i) = \frac{n(n+1)^2}{4}
\]

et sa variance est :
\[
\mathbb{V}(S) = \sum_{i = 1}^n \mathbb{V}(i T_i) = \frac{n^2(n+1)^2(n-1)}{144}
\]

** Test de Spearman : résolution 		    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t      
   :END: 

- Lorsque que l'on obtient un classement identique pour $X$ et $Y$ alors :   

\[
R_i = Q_i \Longrightarrow S_{max} = \sum_{i = 1} i^2 
\]

- Par opposition, lorsque les classements sont opposés  on :
\[
Q_i = n + 1 - R_i \Longrightarrow S_{min} = \sum_{i = 1} i (n + 1 - i)^2 
\]

** Test de Spearman : résolution 		    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t      
   :END: 

- De manière analogique au cas univarié, la statistique de test peut 
  s'écrire en fonction du coéfficient de corrélation de Pearson entre
  $(R_i, Q_i)$. On peut montrer que cette statistique, est une fonction de $S$ : 

\[
r_s = \frac{1}{\sqrt{n - 1}} \frac{S - \mathbb{E}(S)}{\sigma(S)}
\]

\[
r_s = 1 - \frac{6}{n (n^2 - 1)} \sum_{i = 1}^n (R_i - Qi)^2
\]

- $r_s$ est centré autour de son espérance qui est nulle.
- $r_s$ est de variance $\dfrac{1}{n - 1}$
- Pour la suite on posera : $\displaystyle D_i = (R_i - Qi)$

** Test de Spearman : résolution 				    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t
   :END:
Sous $H_0$ : 
- $S$ est asymptotiquement normale donc pour $n$ grand : 
\[
r_s \sqrt{n - 1} \longrightarrow \mathcal{N}(0, 1)
\]

- Pour $11 \leq n \leq 30$ : 

\[
r_s \sqrt{\frac{n - 2}{1 - r^2}} \simeq T_{n - 2}
\]

- On peut aussi construire la région critique à partir de la statistique
\[
S^* = \sum_{i = 1}^n D_i^2
\]

** Test de Spearman : résolution 				    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t
   :END:
- Pour $n$ grand on a :
\[
Z = r_s \sqrt{n - 1}
\]

alors
\[
\alpha = P(Z \geq z_{\alpha} | H_0)
\]

avec $z_{\alpha}$ le fractile d'ordre $1 - \alpha$ de $\mathcal{N}(0, 1)$

- Pour $n$ entre $11$ et $30$, on peut utiliser la statistique suivante
\[
T = r_s \sqrt{\frac{n - 2}{1 - r^2}}
\]
alors
\[
\alpha = P(T \geq t_{\alpha} | H_0)
\]
avec $t_{\alpha}$ le fractile d'ordre $1 - \alpha$ de $T_{n-2}$

** Test de Spearman : résolution 				    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:
*** Ex-aequo 							    :B_block:
    :PROPERTIES:
    :BEAMER_env: block
    :END:
Soit $T_X$ (resp. $T_Y$) l'ensemble des groupes d'ex-aequo dans 
l'échantillon $X$.
Si nous avons $m$ ex-aequo aux rangs $k + 1, ..., k + m$ alors
on les attribue tous le même rang :
\[
k + \frac{m + 1}{2}
\]
Donc on remplace les $m$ ex-aequo par la quantité $k + \dfrac{m + 1}{2}$.


** Test de Spearman : résolution 				    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:
*** Ex-aequo 							    :B_block:
    :PROPERTIES:
    :BEAMER_env: block
    :END:
La procédure de correction des ex-aequo est nécessaire car
en présence de plusieurs ex-aequo, la statistique de test $r_s$
est inflaté. Cette inflation de la statistique de test peut conduire
à rendre la procédure de test trop optimiste. Néanmoins, dans la pratique, quand 
on dispose de peu de ex-aequo l'effet sur la statistique de test est 
minimal.  

** Test de Spearman : résolution 				    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:
*** Ex-aequo 							    :B_block:
    :PROPERTIES:
    :BEAMER_env: block
    :END:
En cas d'ex-aequo, alors la statistique $r_s$ est modifiée :
\[
r_s^* = \frac{1}{2 R^* Q^*}(R^{*2} + Q^{*2} - \sum_{i = 1}^n D_i^2)
\]
 
avec 
- $\displaystyle R^{*2} = \frac{n(n^2 - 1)}{12} - \sum_{m \in T_X} \frac{m^3 - m}{12}$
- $\displaystyle Q^{*2} = \frac{n(n^2 - 1)}{12} - \sum_{m \in T_Y} \frac{m^3 - m}{12}$



** Test de Spearman : exemple 			     :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t
   :END:

*** 								    :B_block:
    :PROPERTIES:
    :BEAMER_env: block
    :BEAMER_col: 0.4   
    :END:
#+begin_src R :exports results 
    df <- data.frame(X = c(1, 1, 2, 2, 3, 4, 5, 6, 7, 8, 8, 12),
                     Y = c(12, 16, 9, 7, 35, 58, 56, 26, 32, 59, 24, 51))
  df
#+end_src

*** 								   :B_column:
    :PROPERTIES:
    :BEAMER_env: column
    :BEAMER_col: 0.6
    :END:
#+begin_src R :exports results :results graphics :file ../figures/course4-spear-1.pdf :height 7.5 
  boxplot(df$X, df$Y, xaxt = "n")
  axis(1, at = c(1, 2), labels = c("X", "Y"))
  
#+end_src

** Test de Spearman : exemple 			    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t
   :END:


#+begin_src R :exports code
df <- mutate(df,
      R = rank(X, ties.method = "average"),
      Q = rank(Y, ties.method = "average"),
      Di_sq = (R - Q)^2
      )
#+end_src


#+begin_src R :exports results 
  df <- mutate(df,
                R = rank(X, ties.method = "average"),
                Q = rank(Y, ties.method = "average"),
                Di_sq = (R - Q)^2
                )
  mat <- t(df)
  colnames(mat) <- seq(nrow(df))
  mat
#+end_src

** Test de Spearman : exemple 			    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t
   :END:

#+begin_src R :exports both
    f <- function(n) (n^3 - n) / 12
    get_ties <- function(x) table(x)[table(x) > 1]
    stat_test <- function(r_sq, q_sq, s) 
      (r_sq + q_sq - s) / (2 * sqrt(r_sq * q_sq))
#+end_src

#+begin_src R :exports both
  n <- nrow(df)
  R_star_sq <- f(n) - sum(f(get_ties(df$X)))
  Q_star_sq <- f(n) - sum(f(get_ties(df$Y)))
  S_star <- sum(df$Di_sq)
  r_star <- stat_test(R_star_sq, Q_star_sq, S_star)
  r_theo <- qt(p = 0.95, df = n - 2) * sqrt((1 - r_star) / (n - 2))
  c(r_star = r_star, r_theo = r_theo, S_star = S_star)
  
#+end_src

** Test de Spearman : exemple 			    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t
   :END:

#+begin_src R :exports both
  r_star > r_theo 
#+end_src

On ne peut rejetter l'hypothèse nulle de dépendance positive entre $X$ et $Y$ au seuil de 5%.

** Test de Spearman : exemple 			    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t
   :END:



#+begin_src R :exports both
  cor.test(df$X, df$Y, method = "spearman", alternative = "greater")  
#+end_src

* Test de Kendall
#+LATEX:\begin{frame}{Plan}
#+LATEX:\tableofcontents[currentsection]
#+LATEX:\end{frame}
** Test de Kendall : résolution 			    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:
    
- Il existe plusieurs tests basés sur les rangs pour tester l'indépendance
  de v.a.
- Le test de Kendall est similaire au test de corrélation de rang de Kendall pour
  traiter les problèmes à un échantillon. 
- La construction de ce test est basée sur une mesure du nombre d'interversions par
  rapport à l'ordre d'observation entre des réalisations de $X$ et $Y$.
- Afin de construire les statistiques sur lesquelles seront basées
  le test de Kendall nous allons considerer, la v.a $T$ définie pour
  construire le test de Spearman ($T_i$ est le rang de $Z_i$ avec $Z_i$
  qui représente l'observation de $Y$ associé à $X_{(i)}$)
  
** Test de Kendall : résolution 				    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:

- La statistique de test est basée sur une v.a $V$ dont les caractéristiques sont les suivantes :
  - A chaque couple $(T_i,T_j)$ avec $i < j$ prends $1$
    si il y a pas concordance $(T_i < T_j)$
  - A chaque couple $(T_i,T_j)$ avec $i < j$ prends $1$
    si il y a inversion $(T_i > T_j)$
- Pour tout les couples sur un échantillons de taille $n$, nous avons $C_n^2$ 
  valeurs ($V\ \in \{-1, 1\}$). En notans $S$ la somme des réalisations de la v.a $V$ 
  alors on peut le $\tau$ de Kendall par :
\[
\tau = \frac{S}{C_n^2}
\]

** Test de Kendall : résolution 		    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:
La statistique $S$ peut être utilisé pour construire le test.
Sous $H_0$, la loi de $S$ est tabulée donc ont peut définir les 
région de rejet suivante pour $n \leq 10$ : 
- ${S > s_1}$ : dépendance positive
- ${S < s_2}$ : dépendance négative
- ${S > s_1\ ou\ S < s_2}$ : dépendance quelconque

** Test de Kendall : résolution 				    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t      
   :END: 
Soit $X$ une v.a et $(X_1, ..., X_n)$ un échantillon de $X$.
Le nombre d'accords $Q$ est définie par :

\[
Q = \sum_{i=1}^{n-1}\sum_{j = i+1}^n1_{\mathbb{R_+^*}}(X_i - X_j)
\]

Et le nombre de désaccords $Q^{'}$ est définie par :


\[
Q^{'} = \sum_{i=1}^{n-1}\sum_{j = i+1}^n1_{\mathbb{R_+^*}}(X_j - X_i)
\]

On a alors :

\[
S = Q - Q^{'}
\]

** Test de Kendall : résolution 				    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:

En remplaçant $S$ par sa valeur et en simplifiant on obtient :

\[
\tau = 1 - \frac{4Q}{n(n - 1)}
\]

- Pour un échantillon totalement inversé : $\tau = -1$
- Pour un échantillon totalement ordonné : $\tau = 1$

** Test de Kendall : résolution 				    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t      
   :END: 
\[
\mathbb{E}(Q) = \frac{n(n-1)}{4}
\]

\[
\mathbb{V}(Q) = \frac{n(n-1)(2n + 5)}{72}
\]

Et donc

\[
\mathbb{E}(\tau) = 0
\]

\[
\mathbb{V}(\tau) = \frac{2(2n + 5)}{9n(n - 1)}
\]

** Test de Kendall : résolution 			    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t
   :END:

Sous $H_0$ et pour $n$ grand, la région de rejet est :
-  $\displaystyle {\tau\ >\ z\ \sqrt(\frac{2(2n + 5)}{9n(n - 1)})}$ : dépendance positive
-  $\displaystyle {\tau\ <\ z\ \sqrt(\frac{2(2n + 5)}{9n(n - 1)})}$ : dépendance négative
-  $\displaystyle {|\tau|\ \neq\ z\ \sqrt(\frac{2(2n + 5)}{9n(n - 1)})}$ : dépendance quelconque

$z$ sont les quantiles de loi normale centrée réduite et dépendent de du niveau du test.



** Test de Kendall : exemple 					    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t
   :END:


#+begin_src R :exports both
  cor.test(df$X, df$Y, method = "kendall", alternative = "greater")
#+end_src

