#+TITLE: Échelle sur deux échantillons
#+AUTHOR: Ahmadou H. DICKO
#+DATE: Février 2014
#+startup: beamer
#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [xetex, bigger]
#+LATEX_HEADER: \usepackage{minted}
#+LATEX_HEADER: \usepackage{fancyvrb}
#+LATEX_HEADER: \definecolor{newgray}{rgb}{0.95, 0.95, 0.95}
#+LATEX_HEADER: \newminted{r}{fontsize=\small, bgcolor=newgray}
#+LATEX_HEADER: \DefineVerbatimEnvironment{verbatim}{Verbatim}{fontsize=\small, label=R output, frame=lines, labelposition=topline}
#+LATEX_HEADER: \setmainfont[Mapping=tex-text,Ligatures=Common]{Minion Pro}
#+LATEX_HEADER: \setsansfont[Mapping=tex-text,Ligatures=Common]{Myriad Pro}
#+LATEX_HEADER: \setmathfont[Scale=MatchLowercase]{Minion Pro}
#+LATEX_HEADER: \setmonofont[Scale=0.75]{Source Code Pro}
#+LATEX_HEADER: \institute[ENSAE]{ENSAE}
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)
#+BEAMER_THEME: Boadilla
#+BEAMER_COLOR_THEME: orchid
#+BEAMER_HEADER: \setbeamertemplate{navigation symbols}{}
#+PROPERTY: session *R*
#+PROPERTY: cache yes 
#+PROPERTY: exports both
#+PROPERTY: tangle yes
#+PROPERTY: results output graphics
#+OPTIONS: toc:nil H:2

#+LATEX:\selectlanguage{frenchb}
#+LATEX:\begin{frame}[t]{Plan}
#+LATEX:\tableofcontents
#+LATEX:\end{frame}

* Introduction
#+begin_src R :exports none :results silent :session
  library(Cairo)
  mainfont <- "Minion Pro"
  CairoFonts(regular = paste(mainfont, "style=Regular", sep=":"),
             bold = paste(mainfont, "style=Bold", sep=":"),
             italic = paste(mainfont, "style=Italic", sep=":"),
             bolditalic = paste(mainfont, "style=Bold Italic,BoldItalic", sep=":"))
  pdf <- CairoPDF
  options(prompt = "> ")
#+end_src
  
** Introduction							    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:
- Lorsque l'on dispose d'un échantillon qui décrit un phénomène donné, il est 
  important de s'intérroger sur le caractère aléatoire des observations.
- Lors de l'étude de série temporelle, une question cruciale est de savoir si les données
  suivent une tendance précise.
- On peut dès lors de procéder à un test /d'échantillon aléatoire/ afin de savoir
  si les fluctuations de l'échantillon sont aléatoires ou déterminées ?
- Deux tests d'hypothèse seront présentés afin de répondre à ces questions :
  - le test de coéfficient du corrélation de rang de Spearman
  - le test de coéfficient du corrélation de rang de Kendall

* Test de Mood
#+LATEX:\begin{frame}{Plan}
#+LATEX:\tableofcontents[currentsection]
#+LATEX:\end{frame}
** Test de Mood : résolution 			    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:
    
- Une alternative au test de corrélation de rang de Spearman est l'utilisation
  du test corrélation de rang de Mood.
-  L'idée de base est comparer l'échantillon naturel $(X_1, ..., X_n)$ et celui
   ordonné $(X_{(1)}, ..., X_{(n)})$ en remarquant que si la tendance est strictement monotone
   alors ces deux échantillons coincident.
- La construction de ce test est basée sur une mesure du nombre d'interversions par
  rapport à l'ordre d'observation.
- Il s'agit alors de construire une statistique basée sur : 

\[
Q = \sum_{i=1}^{n-1}\sum_{j = i+1}^n1_{\mathbb{R_+^*}}(X_i - X_j)
\]

$Q$ permet alors de compter le nombre de fois où pour $i < j$ on a $X_i > X_j$.

** Test de Mood : résolution 			    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t      
   :END: 
- Le nombre maximal possible d'interversion pour un échantillon est égal au nombre 
  de couple $(i, j)$ avec $i < j$ :    
\[
Q_{max} = C_n^2 = \frac{n(n-1)}{2}
\]

- Le nombre minimal possible d'inversion pour un échantillon est nul  
\[
Q_{min} = 0
\]

- La loi de $Q$ peut être obtenu par la fonction génératrice des moments

** Test de Mood : résolution 			    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:

On appelle coefficient de corrélation de rang Mann et Whitney, la
statistique $\tau$ définie par :
\[
\tau = 1 - \frac{4Q}{n(n - 1)}
\]

- avec $Q$ défini plus haut
- Pour un échantillon totalement inversé : $\tau = -1$
- Pour un échantillon totalement ordonné : $\tau = 1$

** Test de Mood : résolution 			    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t      
   :END: 
\[
\mathbb{E}(Q) = \frac{n(n-1)}{4}
\]

\[
\mathbb{V}(Q) = \frac{n(n-1)(2n + 5)}{72}
\]

Et donc

\[
\mathbb{E}(\tau) = 0
\]

\[
\mathbb{V}(\tau) = \frac{2(2n + 5)}{9n(n - 1)}
\]

** Test de Mood : résolution 			    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t
   :END:

Sous $H_0$ et pour $n$ grand, la région de rejet est :
-  $\displaystyle {\tau > z_1 \sqrt(\frac{2(2n + 5)}{9n(n - 1)})}$ : dépendance positive
-  $\displaystyle {\tau < z_2 \sqrt(\frac{2(2n + 5)}{9n(n - 1)})}$ : dépendance négative
-  $\displaystyle {|\tau| > z \sqrt(\frac{2(2n + 5)}{9n(n - 1)})}$ : dépendance quelconque

$z$, $z_1$, $z_2$ sont les quantiles de loi normale centrée réduite et dépendent de du niveau du test
et son caractère (unilatéral, bilatéral)

** Test de Mood : résolution 			    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t      
   :END: 
Soit 

\[
Q^{'} = \sum_{i=1}^{n-1}\sum_{j = i+1}^n1_{\mathbb{R_+^*}}(X_j - X_i)
\]

Pour $n \leq 10$, on peut montrer (exercice) que 

\[
\tau = \frac{S}{C_n^2}
\]

avec 

\[
S = Q - Q^{'}
\]

** Test de Mood : résolution 		            :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t
   :END:
Sous $H_0$, la loi de $S$ est tabulée donc ont peut définir les 
région de rejet suivante pour $n \leq 10$ : 
- ${S > s_1}$ : dépendance positive
- ${S < s_2}$ : dépendance négative
- ${|S| > s}$ : dépendance quelconque

$s$, $s_1$, $s_2$ son issue de la loi de $S$ tabulée et dépendent de du niveau du test
  et son caractère (unilatéral, bilatéral)

** Test de Mood : exemple 			    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:

*** 								   :B_column:
    :PROPERTIES:
    :BEAMER_col: 0.4   
    :BEAMER_env: block
    :END:
#+begin_src R :exports results 
  X <- c(111, 107, 100, 99, 102, 106, 109, 108, 104, 99,
         101, 96, 97, 102, 107, 113, 116, 113, 110, 98)
  Y <- c(107, 108, 106, 98, 105, 103, 110, 105, 104,
         100, 96, 108, 103, 104, 114, 114, 113, 108, 106, 99)
  df <- data.frame(X, Y)
  head(df, 10)
#+end_src

*** 								   :B_column:
    :PROPERTIES:
    :BEAMER_env: column
    :BEAMER_col: 0.6
    :END:
#+begin_src R :exports results :results graphics :file ../figures/course4-spear-1.pdf :height 7 
  boxplot(X, Y, xaxt = "n")
  axis(1, at = c(1, 2), labels = c("X", "Y"))
  
#+end_src
   
** Test de Mood : exemple 			    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:

#+begin_src R
     mood.test(X, Y)
#+end_src

* Test de Ansari-Bradley
#+LATEX:\begin{frame}{Plan}
#+LATEX:\tableofcontents[currentsection]
#+LATEX:\end{frame}
** Test de Ansari-Bradley : résolution 			    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:
    
- Une alternative au test de corrélation de rang de Spearman est l'utilisation
  du test corrélation de rang de Ansari-Bradley.
-  L'idée de base est comparer l'échantillon naturel $(X_1, ..., X_n)$ et celui
   ordonné $(X_{(1)}, ..., X_{(n)})$ en remarquant que si la tendance est strictement monotone
   alors ces deux échantillons coincident.
- La construction de ce test est basée sur une mesure du nombre d'interversions par
  rapport à l'ordre d'observation.
- Il s'agit alors de construire une statistique basée sur : 

\[
Q = \sum_{i=1}^{n-1}\sum_{j = i+1}^n1_{\mathbb{R_+^*}}(X_i - X_j)
\]

$Q$ permet alors de compter le nombre de fois où pour $i < j$ on a $X_i > X_j$.

** Test de Ansari-Bradley : résolution 			    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t      
   :END: 
- Le nombre maximal possible d'interversion pour un échantillon est égal au nombre 
  de couple $(i, j)$ avec $i < j$ :    
\[
Q_{max} = C_n^2 = \frac{n(n-1)}{2}
\]

- Le nombre minimal possible d'inversion pour un échantillon est nul  
\[
Q_{min} = 0
\]

- La loi de $Q$ peut être obtenu par la fonction génératrice des moments

** Test de Ansari-Bradley : résolution 			    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:

On appelle coefficient de corrélation de rang Mann et Whitney, la
statistique $\tau$ définie par :
\[
\tau = 1 - \frac{4Q}{n(n - 1)}
\]

- avec $Q$ défini plus haut
- Pour un échantillon totalement inversé : $\tau = -1$
- Pour un échantillon totalement ordonné : $\tau = 1$

** Test de Ansari-Bradley : résolution 			    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t      
   :END: 
\[
\mathbb{E}(Q) = \frac{n(n-1)}{4}
\]

\[
\mathbb{V}(Q) = \frac{n(n-1)(2n + 5)}{72}
\]

Et donc

\[
\mathbb{E}(\tau) = 0
\]

\[
\mathbb{V}(\tau) = \frac{2(2n + 5)}{9n(n - 1)}
\]

** Test de Ansari-Bradley : résolution 			    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t
   :END:

Sous $H_0$ et pour $n$ grand, la région de rejet est :
-  $\displaystyle {\tau > z_1 \sqrt(\frac{2(2n + 5)}{9n(n - 1)})}$ : dépendance positive
-  $\displaystyle {\tau < z_2 \sqrt(\frac{2(2n + 5)}{9n(n - 1)})}$ : dépendance négative
-  $\displaystyle {|\tau| > z \sqrt(\frac{2(2n + 5)}{9n(n - 1)})}$ : dépendance quelconque

$z$, $z_1$, $z_2$ sont les quantiles de loi normale centrée réduite et dépendent de du niveau du test
et son caractère (unilatéral, bilatéral)

** Test de Ansari-Bradley : résolution 			    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t      
   :END: 
Soit 

\[
Q^{'} = \sum_{i=1}^{n-1}\sum_{j = i+1}^n1_{\mathbb{R_+^*}}(X_j - X_i)
\]

Pour $n \leq 10$, on peut montrer (exercice) que 

\[
\tau = \frac{S}{C_n^2}
\]

avec 

\[
S = Q - Q^{'}
\]

** Test de Ansari-Bradley : résolution 		            :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :BEAMER_OPT: t
   :END:
Sous $H_0$, la loi de $S$ est tabulée donc ont peut définir les 
région de rejet suivante pour $n \leq 10$ : 
- ${S > s_1}$ : dépendance positive
- ${S < s_2}$ : dépendance négative
- ${|S| > s}$ : dépendance quelconque

$s$, $s_1$, $s_2$ son issue de la loi de $S$ tabulée et dépendent de du niveau du test
  et son caractère (unilatéral, bilatéral)

** Test de Ansari-Bradley : exemple 				    :B_frame:
   :PROPERTIES:
   :BEAMER_env: frame
   :END:

#+begin_src R
  ansari.test(X, Y)
#+end_src

